spring:
  application:
    name: eureka-server
  config:
    import: configserver:http://localhost:8888

server:
  port: 8765

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8765/eureka